#!/bin/bash

for MODEL in X7 XLITE X9D X9D+ X9E X10 X12S SKY9X 9XRPRO; do
    pushd .
    DIR=build-${MODEL}
    mkdir -p ${DIR}
    cd ${DIR}
    rm CMakeCache.txt
#    cmake  -DMULTIMODULE=ON -DLUA_COMPILER=ON -DLOG_TELEMETRY=ON -DHELI=OFF -DFLIGHT_MODES=OFF -DGVARS=OFF -DDANGEROUS_MODULE_FUNCTIONS=ON -DPCB=${MODEL} ../
    cmake  -DMULTIMODULE=ON -DLUA_COMPILER=ON -DLOG_TELEMETRY=ON -DHELI=OFF -DDANGEROUS_MODULE_FUNCTIONS=ON -DPCB=${MODEL} ../
    PATH=${OPENTX_ARM_TOOLCHAIN_PATH}:${PATH} make firmware
    popd
done
